package com.dewdrop.loliga.model

object Data {

  object Tournaments {
    val loliga: Tournament = Tournament("LOLiga", Link.tournament(j = 49, f = 24, z = "48bf23e73bd0f2bcaca94a707b2dd686"))
    val other: Tournament = Tournament("Other", Link.noLink)
    val euro: Tournament = Tournament("Euro", Link.noLink)
    val cup: Tournament = Tournament("Cup", Link.noLink)
    val nation: Tournament = Tournament("Nation", Link.noLink)
  }

  import Tournaments._

  object SeasonData extends Season {
    override val name = "LOLiga: 24-й сезон"
    override val version = "3.0"
    override val participantsOnly: Boolean = false

    private object TeamsWithMinutes {
      // @formatter:off
      val athletic: Team = Team("Атлетик Бильбао", Link.team(792, "d89f5fb16937bf7422d14ff627b98956"), euroPlayer = false, participate = false)
      val atletico: Team = Team("Атлетико Мадрид", Link.team(793, "b4b7dd00ecd23896be7cbf417b05a814"), euroPlayer = false, participate = false)
      val barcelona: Team = Team("Барселона", Link.team(795, "681f94e463bd2ae01791e493c5a4bfc7"), euroPlayer = true, participate = false)
      val betis: Team = Team("Бетис", Link.team(796, "9abe7d8e6a577a7cdf7c3f0b58cc500a"), euroPlayer = false, participate = false)
      val valencia: Team = Team("Валенсия", Link.team(826, "4922099bb4660233682c3ad5ee406398"), euroPlayer = true, participate = false)
      val depor: Team = Team("Депортиво", Link.team(800, "5290c3ac1819cf6051d732f2df1b7484"), euroPlayer = false, participate = false)
      val compostela: Team = Team("Компостела", Link.team(799, "91c0f46a5dd8425ad62fefaad68e2035"), euroPlayer = false, participate = false)
      val palmas: Team = Team("Лас Пальмас", Link.team(807, "1f0b7594a04292d10f25ce0607c6a3b2"), euroPlayer = false, participate = false)
      val levante: Team = Team("Леванте", Link.team(809, "fae70910c570081ec974c7d139b8b34c"), euroPlayer = false, participate = false)
      val malaga: Team = Team("Малага", Link.team(810, "0a981fec6985c2273b206fe62f192aee"), euroPlayer = true, participate = false)
      val mallorca: Team = Team("Мальорка", Link.team(811, "0295cbc439503a3257ab3807555bda07"), euroPlayer = false, participate = false)
      //      val murcia: Team = Team("Мурсия", Link.team(1635, "57f3d18dd2d4f8ac0015b0264d211454"), euroPlayer = false, participate = false)
      val osasuna: Team = Team("Осасуна", Link.team(814, "dc5e42bdcd014dd50b4565c4befc9f1f"), euroPlayer = false, participate = false)
      val rayo: Team = Team("Райо Вальекано", Link.team(817, "582ec131d7b8994660f2898a62589f30"), euroPlayer = false, participate = false)
      val real: Team = Team("Реал Мадрид", Link.team(818, "534bfaa8d12b5650da603d7b207fd8e8"), euroPlayer = true, participate = false)
      val sociedad: Team = Team("Реал Сосьедад", Link.team(819, "798a87a66ea104894b7fdd4dd8421eb5"), euroPlayer = false, participate = false)
      //      val jaen: Team = Team("Реал Хаен", Link.team(1622, "ed07be3e312dc1f9198fc6dfae503949"), euroPlayer = false, participate = false)
      val sevilla: Team = Team("Севилья", Link.team(822, "192038a87c9d2a4feb812b2ef9f09d3f"), euroPlayer = false, participate = false)
      val celta: Team = Team("Сельта", Link.team(797, "34c0d53160b454e243beb4e33f34c326"), euroPlayer = false, participate = false)
      val tenerife: Team = Team("Тенерифе", Link.team(824, "2dfcbe307e5882a3cf6daa5c432389fa"), euroPlayer = true, participate = false)
      val huesca: Team = Team("Уэска", Link.team(821, "d0e0f758987648135d418c3904f2ed86"), euroPlayer = false, participate = false)
      //      val getafe: Team = Team("Хетафе", Link.team(806, "208d2036658324079a53c158e73cdf15"), euroPlayer = false, participate = false)
      val espanyol: Team = Team("Эспаньол", Link.team(804, "51c788a7a8e248390ab972bce9b26854"), euroPlayer = false, participate = false)
      // @formatter:on
    }

    val spain: Team = Team.nationTeam("Испания", Link.nationTeam(172, "f4ae367fc9c7fdaa0f0c5ba76e60a6e2"))
    val spainU21: Team = Team.nationTeam("Испания (мол.)", Link.nationTeam(1172, "e776025c328869de54cc135992d1b34d"))
    private val otherNation: Team = Team.nationTeam("Другие", Link.noLink)

    import TeamsWithMinutes._

    protected override val matchDays: Seq[FixtureRound] = Seq(
      TournamentRound(loliga, round = 1, date = LocalDate(year = 2026, month = 7, day = 1), link = Link.round(j = 49, n = 1, z = s"ef8238784b40512d1613b653486567ff")) -> Seq(
        Fixture(valencia, mallorca),
        Fixture(athletic, palmas),
        Fixture(real, huesca),
        Fixture(rayo, malaga),
        Fixture(celta, compostela),
        Fixture(levante, depor),
        Fixture(barcelona, atletico),
        Fixture(betis, sevilla),
        Fixture(sociedad, espanyol),
        Fixture(tenerife, osasuna),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 7, day = 3), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 2, date = LocalDate(year = 2026, month = 7, day = 6), link = Link.round(j = 49, n = 2, z = s"c8ce87920b98bc2b3c17e8aaf00b2c46")) -> Seq(
        Fixture(osasuna, betis),
        Fixture(compostela, athletic),
        Fixture(palmas, rayo),
        Fixture(depor, valencia),
        Fixture(huesca, celta),
        Fixture(espanyol, tenerife),
        Fixture(malaga, sociedad),
        Fixture(mallorca, real),
        Fixture(atletico, levante),
        Fixture(sevilla, barcelona),
      ),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 7, day = 8), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 3, date = LocalDate(year = 2026, month = 7, day = 10), link = Link.round(j = 49, n = 3, z = s"660435b343787249437f31264d0c6310")) -> Seq(
        Fixture(valencia, palmas),
        Fixture(athletic, huesca),
        Fixture(real, betis),
        Fixture(rayo, mallorca),
        Fixture(celta, atletico),
        Fixture(espanyol, malaga),
        Fixture(levante, compostela),
        Fixture(barcelona, osasuna),
        Fixture(sociedad, sevilla),
        Fixture(tenerife, depor),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 7, day = 13), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 7, day = 14), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 7, day = 15), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 4, date = LocalDate(year = 2026, month = 7, day = 17), link = Link.round(j = 49, n = 4, z = s"1eb2b5cbd72808f07839f032ae6a11c0")) -> Seq(
        Fixture(osasuna, real),
        Fixture(compostela, rayo),
        Fixture(palmas, espanyol),
        Fixture(depor, sociedad),
        Fixture(huesca, barcelona),
        Fixture(malaga, tenerife),
        Fixture(betis, athletic),
        Fixture(mallorca, celta),
        Fixture(atletico, valencia),
        Fixture(sevilla, levante),
      ),
      TournamentRound(loliga, round = 5, date = LocalDate(year = 2026, month = 7, day = 20), link = Link.round(j = 49, n = 5, z = s"8b4696a58b8b6f01442f74a44abeb057")) -> Seq(
        Fixture(valencia, sevilla),
        Fixture(athletic, malaga),
        Fixture(real, compostela),
        Fixture(rayo, atletico),
        Fixture(celta, osasuna),
        Fixture(espanyol, depor),
        Fixture(levante, mallorca),
        Fixture(barcelona, palmas),
        Fixture(sociedad, huesca),
        Fixture(tenerife, betis),
      ),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 7, day = 22), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 6, date = LocalDate(year = 2026, month = 7, day = 24), link = Link.round(j = 49, n = 6, z = s"022b0d82ea3bd7db3a9b087d36095e55")) -> Seq(
        Fixture(osasuna, levante),
        Fixture(compostela, barcelona),
        Fixture(palmas, tenerife),
        Fixture(celta, athletic),
        Fixture(huesca, espanyol),
        Fixture(malaga, real),
        Fixture(betis, valencia),
        Fixture(mallorca, sociedad),
        Fixture(atletico, depor),
        Fixture(sevilla, rayo),
      ),
      TournamentRound(loliga, round = 7, date = LocalDate(year = 2026, month = 7, day = 27), link = Link.round(j = 49, n = 7, z = s"f70cbf989a577873e48756a07e7dfd5c")) -> Seq(
        Fixture(valencia, osasuna),
        Fixture(athletic, sevilla),
        Fixture(depor, huesca),
        Fixture(real, atletico),
        Fixture(rayo, celta),
        Fixture(espanyol, compostela),
        Fixture(levante, malaga),
        Fixture(barcelona, betis),
        Fixture(sociedad, palmas),
        Fixture(tenerife, mallorca),
      ),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 7, day = 28), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 7, day = 29), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 8, date = LocalDate(year = 2026, month = 7, day = 31), link = Link.round(j = 49, n = 8, z = s"085ff76b4b3c4ec9fc1ba887a07bc05c")) -> Seq(
        Fixture(osasuna, sociedad),
        Fixture(compostela, palmas),
        Fixture(celta, espanyol),
        Fixture(huesca, rayo),
        Fixture(barcelona, valencia),
        Fixture(malaga, depor),
        Fixture(betis, levante),
        Fixture(mallorca, athletic),
        Fixture(atletico, tenerife),
        Fixture(sevilla, real),
      ),
      TournamentRound(loliga, round = 9, date = LocalDate(year = 2026, month = 8, day = 3), link = Link.round(j = 49, n = 9, z = s"353b0c1da34e6dc071e2910e9948570b")) -> Seq(
        Fixture(palmas, celta),
        Fixture(athletic, osasuna),
        Fixture(depor, compostela),
        Fixture(real, barcelona),
        Fixture(rayo, valencia),
        Fixture(espanyol, atletico),
        Fixture(levante, huesca),
        Fixture(malaga, mallorca),
        Fixture(sociedad, betis),
        Fixture(tenerife, sevilla),
      ),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 8, day = 5), link = Link.noLink) -> Seq(),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 8, day = 7), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 10, date = LocalDate(year = 2026, month = 8, day = 10), link = Link.round(j = 49, n = 10, z = s"caac75443a60bc021ad100c47bf0e692")) -> Seq(
        Fixture(osasuna, rayo),
        Fixture(valencia, real),
        Fixture(celta, depor),
        Fixture(huesca, tenerife),
        Fixture(levante, espanyol),
        Fixture(barcelona, sociedad),
        Fixture(betis, palmas),
        Fixture(mallorca, compostela),
        Fixture(atletico, athletic),
        Fixture(sevilla, malaga),
      ),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 8, day = 11), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 8, day = 12), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 11, date = LocalDate(year = 2026, month = 8, day = 14), link = Link.round(j = 49, n = 11, z = s"464eac516b36f5fcfe4c458bb0b66606")) -> Seq(
        Fixture(compostela, betis),
        Fixture(palmas, osasuna),
        Fixture(athletic, valencia),
        Fixture(depor, mallorca),
        Fixture(rayo, barcelona),
        Fixture(huesca, atletico),
        Fixture(espanyol, sevilla),
        Fixture(malaga, celta),
        Fixture(sociedad, real),
        Fixture(tenerife, levante),
      ),
      TournamentRound(loliga, round = 12, date = LocalDate(year = 2026, month = 8, day = 17), link = Link.round(j = 49, n = 12, z = s"54c1a4ba1e92fca5d50a781d6211503c")) -> Seq(
        Fixture(osasuna, compostela),
        Fixture(valencia, sociedad),
        Fixture(real, depor),
        Fixture(rayo, levante),
        Fixture(celta, tenerife),
        Fixture(barcelona, athletic),
        Fixture(betis, huesca),
        Fixture(mallorca, espanyol),
        Fixture(atletico, malaga),
        Fixture(sevilla, palmas),
      ),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 8, day = 19), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 13, date = LocalDate(year = 2026, month = 8, day = 21), link = Link.round(j = 49, n = 13, z = s"cba2174e22d84ecee4f35ffb53c1a9a1")) -> Seq(
        Fixture(compostela, valencia),
        Fixture(palmas, real),
        Fixture(athletic, sociedad),
        Fixture(depor, barcelona),
        Fixture(huesca, sevilla),
        Fixture(espanyol, betis),
        Fixture(levante, celta),
        Fixture(malaga, osasuna),
        Fixture(mallorca, atletico),
        Fixture(tenerife, rayo),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 8, day = 24), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 8, day = 25), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 8, day = 26), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 14, date = LocalDate(year = 2026, month = 8, day = 28), link = Link.round(j = 49, n = 14, z = s"5d597f3888a92a18aaea5347096e6302")) -> Seq(
        Fixture(osasuna, espanyol),
        Fixture(valencia, huesca),
        Fixture(palmas, malaga),
        Fixture(real, athletic),
        Fixture(rayo, depor),
        Fixture(barcelona, tenerife),
        Fixture(betis, celta),
        Fixture(sociedad, levante),
        Fixture(atletico, compostela),
        Fixture(sevilla, mallorca),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 8, day = 31), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 15, date = LocalDate(year = 2026, month = 9, day = 2), link = Link.round(j = 49, n = 15, z = s"20cb752e435b6226893e1341216fbc48")) -> Seq(
        Fixture(compostela, sociedad),
        Fixture(depor, athletic),
        Fixture(celta, sevilla),
        Fixture(huesca, osasuna),
        Fixture(espanyol, rayo),
        Fixture(levante, valencia),
        Fixture(malaga, betis),
        Fixture(mallorca, barcelona),
        Fixture(atletico, palmas),
        Fixture(tenerife, real),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 9, day = 4), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 9, day = 7), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 9, day = 8), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 16, date = LocalDate(year = 2026, month = 9, day = 9), link = Link.round(j = 49, n = 16, z = s"3565b9413f7fc6ecfddabbb90b94dd27")) -> Seq(
        Fixture(osasuna, mallorca),
        Fixture(compostela, malaga),
        Fixture(valencia, celta),
        Fixture(palmas, huesca),
        Fixture(athletic, levante),
        Fixture(real, rayo),
        Fixture(barcelona, espanyol),
        Fixture(betis, atletico),
        Fixture(sociedad, tenerife),
        Fixture(sevilla, depor),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 9, day = 11), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 9, day = 14), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 17, date = LocalDate(year = 2026, month = 9, day = 16), link = Link.round(j = 49, n = 17, z = s"98daeaa98b1a4b137fe0330c6d20ea68")) -> Seq(
        Fixture(depor, osasuna),
        Fixture(rayo, betis),
        Fixture(celta, sociedad),
        Fixture(huesca, compostela),
        Fixture(espanyol, athletic),
        Fixture(levante, real),
        Fixture(malaga, barcelona),
        Fixture(mallorca, palmas),
        Fixture(atletico, sevilla),
        Fixture(tenerife, valencia),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 9, day = 18), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 9, day = 21), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 9, day = 22), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 18, date = LocalDate(year = 2026, month = 9, day = 23), link = Link.round(j = 49, n = 18, z = s"039b62edc03ebf874aa94384a228980b")) -> Seq(
        Fixture(osasuna, atletico),
        Fixture(compostela, sevilla),
        Fixture(valencia, malaga),
        Fixture(palmas, levante),
        Fixture(athletic, tenerife),
        Fixture(real, espanyol),
        Fixture(huesca, mallorca),
        Fixture(barcelona, celta),
        Fixture(betis, depor),
        Fixture(sociedad, rayo),
      ),
      TournamentRound(loliga, round = 19, date = LocalDate(year = 2026, month = 9, day = 25), link = Link.round(j = 49, n = 19, z = s"082d3bfb3dae291c25fc90ecbfd6c65f")) -> Seq(
        Fixture(depor, palmas),
        Fixture(rayo, athletic),
        Fixture(celta, real),
        Fixture(espanyol, valencia),
        Fixture(levante, barcelona),
        Fixture(malaga, huesca),
        Fixture(mallorca, betis),
        Fixture(atletico, sociedad),
        Fixture(sevilla, osasuna),
        Fixture(tenerife, compostela),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 9, day = 28), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 9, day = 30), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 20, date = LocalDate(year = 2026, month = 10, day = 2), link = Link.round(j = 49, n = 20, z = s"c54995a10b4602f3f33efe3b06a6efb5")) -> Seq(
        Fixture(mallorca, valencia),
        Fixture(palmas, athletic),
        Fixture(huesca, real),
        Fixture(malaga, rayo),
        Fixture(compostela, celta),
        Fixture(depor, levante),
        Fixture(atletico, barcelona),
        Fixture(sevilla, betis),
        Fixture(espanyol, sociedad),
        Fixture(osasuna, tenerife),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 10, day = 5), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 10, day = 6), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 10, day = 7), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 21, date = LocalDate(year = 2026, month = 10, day = 9), link = Link.round(j = 49, n = 21, z = s"9c95978287651bbb2fd47804dc4e18e7")) -> Seq(
        Fixture(betis, osasuna),
        Fixture(athletic, compostela),
        Fixture(rayo, palmas),
        Fixture(valencia, depor),
        Fixture(celta, huesca),
        Fixture(tenerife, espanyol),
        Fixture(sociedad, malaga),
        Fixture(real, mallorca),
        Fixture(levante, atletico),
        Fixture(barcelona, sevilla),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 10, day = 12), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 10, day = 14), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 22, date = LocalDate(year = 2026, month = 10, day = 16), link = Link.round(j = 49, n = 22, z = s"2ba9b7c4302404b9a9835f9b0c493a3d")) -> Seq(
        Fixture(palmas, valencia),
        Fixture(huesca, athletic),
        Fixture(betis, real),
        Fixture(mallorca, rayo),
        Fixture(atletico, celta),
        Fixture(malaga, espanyol),
        Fixture(compostela, levante),
        Fixture(osasuna, barcelona),
        Fixture(sevilla, sociedad),
        Fixture(depor, tenerife),
      ),
      TournamentRound(loliga, round = 23, date = LocalDate(year = 2026, month = 10, day = 19), link = Link.round(j = 49, n = 23, z = s"e68f86870ed797cd22cd2409dc73b2e2")) -> Seq(
        Fixture(real, osasuna),
        Fixture(rayo, compostela),
        Fixture(espanyol, palmas),
        Fixture(sociedad, depor),
        Fixture(barcelona, huesca),
        Fixture(tenerife, malaga),
        Fixture(athletic, betis),
        Fixture(celta, mallorca),
        Fixture(valencia, atletico),
        Fixture(levante, sevilla),
      ),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 10, day = 20), link = Link.noLink) -> Seq(),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 10, day = 21), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 10, day = 23), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 24, date = LocalDate(year = 2026, month = 10, day = 26), link = Link.round(j = 49, n = 24, z = s"1eb29c96fbd2456948e918a2ac2bf0f8")) -> Seq(
        Fixture(sevilla, valencia),
        Fixture(malaga, athletic),
        Fixture(compostela, real),
        Fixture(atletico, rayo),
        Fixture(osasuna, celta),
        Fixture(depor, espanyol),
        Fixture(mallorca, levante),
        Fixture(palmas, barcelona),
        Fixture(huesca, sociedad),
        Fixture(betis, tenerife),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 10, day = 28), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 10, day = 30), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 25, date = LocalDate(year = 2026, month = 11, day = 2), link = Link.round(j = 49, n = 25, z = s"61a11106e44ab2c07e4c86043cf13d32")) -> Seq(
        Fixture(levante, osasuna),
        Fixture(barcelona, compostela),
        Fixture(tenerife, palmas),
        Fixture(athletic, celta),
        Fixture(espanyol, huesca),
        Fixture(real, malaga),
        Fixture(valencia, betis),
        Fixture(sociedad, mallorca),
        Fixture(depor, atletico),
        Fixture(rayo, sevilla),
      ),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 11, day = 3), link = Link.noLink) -> Seq(),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 11, day = 4), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 26, date = LocalDate(year = 2026, month = 11, day = 6), link = Link.round(j = 49, n = 26, z = s"cc0acf9464434394cc1e82b629937d90")) -> Seq(
        Fixture(osasuna, valencia),
        Fixture(sevilla, athletic),
        Fixture(huesca, depor),
        Fixture(atletico, real),
        Fixture(celta, rayo),
        Fixture(compostela, espanyol),
        Fixture(malaga, levante),
        Fixture(betis, barcelona),
        Fixture(palmas, sociedad),
        Fixture(mallorca, tenerife),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 11, day = 9), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 11, day = 11), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 27, date = LocalDate(year = 2026, month = 11, day = 13), link = Link.round(j = 49, n = 27, z = s"becd34100435ae0dc733e63ea2be1749")) -> Seq(
        Fixture(sociedad, osasuna),
        Fixture(palmas, compostela),
        Fixture(espanyol, celta),
        Fixture(rayo, huesca),
        Fixture(valencia, barcelona),
        Fixture(depor, malaga),
        Fixture(levante, betis),
        Fixture(athletic, mallorca),
        Fixture(tenerife, atletico),
        Fixture(real, sevilla),
      ),
      TournamentRound(loliga, round = 28, date = LocalDate(year = 2026, month = 11, day = 16), link = Link.round(j = 49, n = 28, z = s"2be54b100fa510e808475bab87b9d9b8")) -> Seq(
        Fixture(celta, palmas),
        Fixture(osasuna, athletic),
        Fixture(compostela, depor),
        Fixture(barcelona, real),
        Fixture(valencia, rayo),
        Fixture(atletico, espanyol),
        Fixture(huesca, levante),
        Fixture(mallorca, malaga),
        Fixture(betis, sociedad),
        Fixture(sevilla, tenerife),
      ),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 11, day = 17), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 11, day = 18), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 29, date = LocalDate(year = 2026, month = 11, day = 20), link = Link.round(j = 49, n = 29, z = s"cc6d44a81423cfb511876d86f5637793")) -> Seq(
        Fixture(rayo, osasuna),
        Fixture(real, valencia),
        Fixture(depor, celta),
        Fixture(tenerife, huesca),
        Fixture(espanyol, levante),
        Fixture(sociedad, barcelona),
        Fixture(palmas, betis),
        Fixture(compostela, mallorca),
        Fixture(athletic, atletico),
        Fixture(malaga, sevilla),
      ),
      TournamentRound(loliga, round = 30, date = LocalDate(year = 2026, month = 11, day = 23), link = Link.round(j = 49, n = 30, z = s"1e87c32a7aabf4a74806a71401c22199")) -> Seq(
        Fixture(betis, compostela),
        Fixture(osasuna, palmas),
        Fixture(valencia, athletic),
        Fixture(mallorca, depor),
        Fixture(barcelona, rayo),
        Fixture(atletico, huesca),
        Fixture(sevilla, espanyol),
        Fixture(celta, malaga),
        Fixture(real, sociedad),
        Fixture(levante, tenerife),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 11, day = 25), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 11, day = 27), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 31, date = LocalDate(year = 2026, month = 11, day = 30), link = Link.round(j = 49, n = 31, z = s"8a2e2e77533374504b96f735df6425d6")) -> Seq(
        Fixture(compostela, osasuna),
        Fixture(sociedad, valencia),
        Fixture(depor, real),
        Fixture(levante, rayo),
        Fixture(tenerife, celta),
        Fixture(athletic, barcelona),
        Fixture(huesca, betis),
        Fixture(espanyol, mallorca),
        Fixture(malaga, atletico),
        Fixture(palmas, sevilla),
      ),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 12, day = 1), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 32, date = LocalDate(year = 2026, month = 12, day = 2), link = Link.round(j = 49, n = 32, z = s"04fd6e4d8a02177b9785ac592e25168e")) -> Seq(
        Fixture(valencia, compostela),
        Fixture(real, palmas),
        Fixture(sociedad, athletic),
        Fixture(barcelona, depor),
        Fixture(sevilla, huesca),
        Fixture(betis, espanyol),
        Fixture(celta, levante),
        Fixture(osasuna, malaga),
        Fixture(atletico, mallorca),
        Fixture(rayo, tenerife),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 12, day = 4), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 12, day = 7), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 33, date = LocalDate(year = 2026, month = 12, day = 9), link = Link.round(j = 49, n = 33, z = s"4e5b978f3a209176fab7378411b799c1")) -> Seq(
        Fixture(espanyol, osasuna),
        Fixture(huesca, valencia),
        Fixture(malaga, palmas),
        Fixture(athletic, real),
        Fixture(depor, rayo),
        Fixture(tenerife, barcelona),
        Fixture(celta, betis),
        Fixture(levante, sociedad),
        Fixture(compostela, atletico),
        Fixture(mallorca, sevilla),
      ),
      TournamentRound(loliga, round = 34, date = LocalDate(year = 2026, month = 12, day = 11), link = Link.round(j = 49, n = 34, z = s"76a30bf0fccf1856aa76f8faf7406f88")) -> Seq(
        Fixture(sociedad, compostela),
        Fixture(athletic, depor),
        Fixture(sevilla, celta),
        Fixture(osasuna, huesca),
        Fixture(rayo, espanyol),
        Fixture(valencia, levante),
        Fixture(betis, malaga),
        Fixture(barcelona, mallorca),
        Fixture(palmas, atletico),
        Fixture(real, tenerife),
      ),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 12, day = 14), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2026, month = 12, day = 15), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 35, date = LocalDate(year = 2026, month = 12, day = 16), link = Link.round(j = 49, n = 35, z = s"a747d358541042b7bcf51dc31cc47d9a")) -> Seq(
        Fixture(mallorca, osasuna),
        Fixture(malaga, compostela),
        Fixture(celta, valencia),
        Fixture(huesca, palmas),
        Fixture(levante, athletic),
        Fixture(rayo, real),
        Fixture(espanyol, barcelona),
        Fixture(atletico, betis),
        Fixture(tenerife, sociedad),
        Fixture(depor, sevilla),
      ),
      TournamentRound(cup, round = 0, date = LocalDate(year = 2026, month = 12, day = 18), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 36, date = LocalDate(year = 2026, month = 12, day = 21), link = Link.round(j = 49, n = 36, z = s"2d617e9acae82d79c4f53d8a21890a72")) -> Seq(
        Fixture(osasuna, depor),
        Fixture(betis, rayo),
        Fixture(sociedad, celta),
        Fixture(compostela, huesca),
        Fixture(athletic, espanyol),
        Fixture(real, levante),
        Fixture(barcelona, malaga),
        Fixture(palmas, mallorca),
        Fixture(sevilla, atletico),
        Fixture(valencia, tenerife),
      ),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2026, month = 12, day = 23), link = Link.noLink) -> Seq(),
      TournamentRound(loliga, round = 37, date = LocalDate(year = 2026, month = 12, day = 25), link = Link.round(j = 49, n = 37, z = s"f23f2742a1de15c86f7d954fe567a3d0")) -> Seq(
        Fixture(atletico, osasuna),
        Fixture(sevilla, compostela),
        Fixture(malaga, valencia),
        Fixture(levante, palmas),
        Fixture(tenerife, athletic),
        Fixture(espanyol, real),
        Fixture(mallorca, huesca),
        Fixture(celta, barcelona),
        Fixture(depor, betis),
        Fixture(rayo, sociedad),
      ),
      TournamentRound(loliga, round = 38, date = LocalDate(year = 2026, month = 12, day = 28), link = Link.round(j = 49, n = 38, z = s"7b925f8a1b9ef7360dded6574b9dabe4")) -> Seq(
        Fixture(palmas, depor),
        Fixture(athletic, rayo),
        Fixture(real, celta),
        Fixture(valencia, espanyol),
        Fixture(barcelona, levante),
        Fixture(huesca, malaga),
        Fixture(betis, mallorca),
        Fixture(sociedad, atletico),
        Fixture(osasuna, sevilla),
        Fixture(compostela, tenerife),
      ),
      TournamentRound(other, round = 0, date = LocalDate(year = 2026, month = 12, day = 30), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2027, month = 1, day = 11), link = Link.noLink) -> Seq(),
      TournamentRound(other, round = 0, date = LocalDate(year = 2027, month = 1, day = 13), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2027, month = 1, day = 15), link = Link.noLink) -> Seq(),
      TournamentRound(other, round = 0, date = LocalDate(year = 2027, month = 1, day = 18), link = Link.noLink) -> Seq(),
      TournamentRound(nation, round = 0, date = LocalDate(year = 2027, month = 1, day = 19), link = Link.noLink) -> Seq(),
      TournamentRound(other, round = 0, date = LocalDate(year = 2027, month = 1, day = 20), link = Link.noLink) -> Seq(),
      TournamentRound(euro, round = 0, date = LocalDate(year = 2027, month = 1, day = 22), link = Link.noLink) -> Seq(),
    ).sortBy(_._1.date)
  }
}
