package com.dewdrop.loliga.model

object Data {

  object Tournaments {
    val loliga: Tournament = Tournament("LOLiga", Link.tournament(j = 49, f = 22, z = "592e78899857ec0b1e92b42e865d5ee4"))
  }

  import Tournaments._

  object SeasonData extends Season {
    override val name = "LOLiga: 22-й сезон"
    override val version = "1.0"
    override val participantsOnly: Boolean = true

    private object TeamsWithMinutes {
      // @formatter:off
      val almeria: Team = Team("Альмерия", Link.team(791, "4f8822fc9a8362e121db9bed3aac450b"), euroPlayer = false, participate = true)
      val athletic: Team = Team("Атлетик Бильбао", Link.team(792, "d89f5fb16937bf7422d14ff627b98956"), euroPlayer = false, participate = true)
      val atletico: Team = Team("Атлетико Мадрид", Link.team(793, "b4b7dd00ecd23896be7cbf417b05a814"), euroPlayer = true, participate = true)
      val barcelona: Team = Team("Барселона", Link.team(795, "681f94e463bd2ae01791e493c5a4bfc7"), euroPlayer = true, participate = true)
      val betis: Team = Team("Бетис", Link.team(796, "9abe7d8e6a577a7cdf7c3f0b58cc500a"), euroPlayer = false, participate = true)
      val valencia: Team = Team("Валенсия", Link.team(826, "4922099bb4660233682c3ad5ee406398"), euroPlayer = true, participate = true)
      val levante: Team = Team("Леванте", Link.team(809, "fae70910c570081ec974c7d139b8b34c"), euroPlayer = false, participate = true)
      val malaga: Team = Team("Малага", Link.team(810, "0a981fec6985c2273b206fe62f192aee"), euroPlayer = false, participate = false)
      val mallorca: Team = Team("Мальорка", Link.team(811, "0295cbc439503a3257ab3807555bda07"), euroPlayer = true, participate = true)
      val murcia: Team = Team("Мурсия", Link.team(1635, "57f3d18dd2d4f8ac0015b0264d211454"), euroPlayer = false, participate = false)
      val osasuna: Team = Team("Осасуна", Link.team(814, "dc5e42bdcd014dd50b4565c4befc9f1f"), euroPlayer = false, participate = true)
      val real: Team = Team("Реал Мадрид", Link.team(818, "534bfaa8d12b5650da603d7b207fd8e8"), euroPlayer = false, participate = true)
      val sociedad: Team = Team("Реал Сосьедад", Link.team(819, "798a87a66ea104894b7fdd4dd8421eb5"), euroPlayer = false, participate = false)
      val jaen: Team = Team("Реал Хаен", Link.team(1622, "ed07be3e312dc1f9198fc6dfae503949"), euroPlayer = false, participate = false)
      val zaragoza: Team = Team("Сарагоса", Link.team(830, "e2bc04fda29d34c537c3fe86b9459aed"), euroPlayer = false, participate = true)
      val celta: Team = Team("Сельта", Link.team(797, "34c0d53160b454e243beb4e33f34c326"), euroPlayer = false, participate = true)
      val tenerife: Team = Team("Тенерифе", Link.team(824, "2dfcbe307e5882a3cf6daa5c432389fa"), euroPlayer = true, participate = true)
      val huesca: Team = Team("Уэска", Link.team(821, "d0e0f758987648135d418c3904f2ed86"), euroPlayer = false, participate = true)
      val eibar: Team = Team("Эйбар", Link.team(801, "a0b5838bd20cf719f4ac5085dccdf4c0"), euroPlayer = false, participate = true)
      val espanyol: Team = Team("Эспаньол", Link.team(804, "51c788a7a8e248390ab972bce9b26854"), euroPlayer = false, participate = true)
      // @formatter:on
    }

    import TeamsWithMinutes._

    protected override val matchDays: FixtureList = Seq(
      TournamentRound(loliga, round = 1, date = LocalDate(year = 2024, month = 5, day = 29), link = Link.round(j = 49, n = 1, z = s"ef8238784b40512d1613b653486567ff")) -> Seq(
        Fixture(murcia, mallorca),
        Fixture(huesca, levante),
        Fixture(atletico, jaen),
        Fixture(osasuna, valencia),
        Fixture(espanyol, almeria),
        Fixture(barcelona, athletic),
        Fixture(celta, malaga),
        Fixture(eibar, tenerife),
        Fixture(sociedad, zaragoza),
        Fixture(real, betis),
      ),
      TournamentRound(loliga, round = 2, date = LocalDate(year = 2024, month = 6, day = 3), link = Link.round(j = 49, n = 2, z = s"c8ce87920b98bc2b3c17e8aaf00b2c46")) -> Seq(
        Fixture(mallorca, huesca),
        Fixture(levante, atletico),
        Fixture(jaen, osasuna),
        Fixture(valencia, espanyol),
        Fixture(almeria, barcelona),
        Fixture(athletic, celta),
        Fixture(malaga, eibar),
        Fixture(tenerife, sociedad),
        Fixture(zaragoza, real),
        Fixture(betis, murcia),
      ),
      TournamentRound(loliga, round = 3, date = LocalDate(year = 2024, month = 6, day = 7), link = Link.round(j = 49, n = 3, z = s"660435b343787249437f31264d0c6310")) -> Seq(
        Fixture(murcia, huesca),
        Fixture(atletico, mallorca),
        Fixture(osasuna, levante),
        Fixture(espanyol, jaen),
        Fixture(barcelona, valencia),
        Fixture(celta, almeria),
        Fixture(eibar, athletic),
        Fixture(sociedad, malaga),
        Fixture(real, tenerife),
        Fixture(betis, zaragoza),
      ),
      TournamentRound(loliga, round = 4, date = LocalDate(year = 2024, month = 6, day = 14), link = Link.round(j = 49, n = 4, z = s"1eb2b5cbd72808f07839f032ae6a11c0")) -> Seq(
        Fixture(huesca, atletico),
        Fixture(mallorca, osasuna),
        Fixture(levante, espanyol),
        Fixture(jaen, barcelona),
        Fixture(valencia, celta),
        Fixture(almeria, eibar),
        Fixture(athletic, sociedad),
        Fixture(malaga, real),
        Fixture(tenerife, betis),
        Fixture(zaragoza, murcia),
      ),
      TournamentRound(loliga, round = 5, date = LocalDate(year = 2024, month = 6, day = 17), link = Link.round(j = 49, n = 5, z = s"8b4696a58b8b6f01442f74a44abeb057")) -> Seq(
        Fixture(murcia, atletico),
        Fixture(osasuna, huesca),
        Fixture(espanyol, mallorca),
        Fixture(barcelona, levante),
        Fixture(celta, jaen),
        Fixture(eibar, valencia),
        Fixture(sociedad, almeria),
        Fixture(real, athletic),
        Fixture(betis, malaga),
        Fixture(zaragoza, tenerife),
      ),
      TournamentRound(loliga, round = 6, date = LocalDate(year = 2024, month = 6, day = 21), link = Link.round(j = 49, n = 6, z = s"022b0d82ea3bd7db3a9b087d36095e55")) -> Seq(
        Fixture(atletico, osasuna),
        Fixture(huesca, espanyol),
        Fixture(mallorca, barcelona),
        Fixture(levante, celta),
        Fixture(jaen, eibar),
        Fixture(valencia, sociedad),
        Fixture(almeria, real),
        Fixture(athletic, betis),
        Fixture(malaga, zaragoza),
        Fixture(tenerife, murcia),
      ),
      TournamentRound(loliga, round = 7, date = LocalDate(year = 2024, month = 6, day = 28), link = Link.round(j = 49, n = 7, z = s"f70cbf989a577873e48756a07e7dfd5c")) -> Seq(
        Fixture(murcia, osasuna),
        Fixture(espanyol, atletico),
        Fixture(barcelona, huesca),
        Fixture(celta, mallorca),
        Fixture(eibar, levante),
        Fixture(sociedad, jaen),
        Fixture(real, valencia),
        Fixture(betis, almeria),
        Fixture(zaragoza, athletic),
        Fixture(tenerife, malaga),
      ),
      TournamentRound(loliga, round = 8, date = LocalDate(year = 2024, month = 7, day = 3), link = Link.round(j = 49, n = 8, z = s"085ff76b4b3c4ec9fc1ba887a07bc05c")) -> Seq(
        Fixture(osasuna, espanyol),
        Fixture(atletico, barcelona),
        Fixture(huesca, celta),
        Fixture(mallorca, eibar),
        Fixture(levante, sociedad),
        Fixture(jaen, real),
        Fixture(valencia, betis),
        Fixture(almeria, zaragoza),
        Fixture(athletic, tenerife),
        Fixture(malaga, murcia),
      ),
      TournamentRound(loliga, round = 9, date = LocalDate(year = 2024, month = 7, day = 8), link = Link.round(j = 49, n = 9, z = s"353b0c1da34e6dc071e2910e9948570b")) -> Seq(
        Fixture(murcia, espanyol),
        Fixture(barcelona, osasuna),
        Fixture(celta, atletico),
        Fixture(eibar, huesca),
        Fixture(sociedad, mallorca),
        Fixture(real, levante),
        Fixture(betis, jaen),
        Fixture(zaragoza, valencia),
        Fixture(tenerife, almeria),
        Fixture(malaga, athletic),
      ),
      TournamentRound(loliga, round = 10, date = LocalDate(year = 2024, month = 7, day = 15), link = Link.round(j = 49, n = 10, z = s"caac75443a60bc021ad100c47bf0e692")) -> Seq(
        Fixture(espanyol, barcelona),
        Fixture(osasuna, celta),
        Fixture(atletico, eibar),
        Fixture(huesca, sociedad),
        Fixture(mallorca, real),
        Fixture(levante, betis),
        Fixture(jaen, zaragoza),
        Fixture(valencia, tenerife),
        Fixture(almeria, malaga),
        Fixture(athletic, murcia),
      ),
      TournamentRound(loliga, round = 11, date = LocalDate(year = 2024, month = 7, day = 19), link = Link.round(j = 49, n = 11, z = s"464eac516b36f5fcfe4c458bb0b66606")) -> Seq(
        Fixture(murcia, barcelona),
        Fixture(celta, espanyol),
        Fixture(eibar, osasuna),
        Fixture(sociedad, atletico),
        Fixture(real, huesca),
        Fixture(betis, mallorca),
        Fixture(zaragoza, levante),
        Fixture(tenerife, jaen),
        Fixture(malaga, valencia),
        Fixture(athletic, almeria),
      ),
      TournamentRound(loliga, round = 12, date = LocalDate(year = 2024, month = 7, day = 24), link = Link.round(j = 49, n = 12, z = s"54c1a4ba1e92fca5d50a781d6211503c")) -> Seq(
        Fixture(barcelona, celta),
        Fixture(espanyol, eibar),
        Fixture(osasuna, sociedad),
        Fixture(atletico, real),
        Fixture(huesca, betis),
        Fixture(mallorca, zaragoza),
        Fixture(levante, tenerife),
        Fixture(jaen, malaga),
        Fixture(valencia, athletic),
        Fixture(almeria, murcia),
      ),
      TournamentRound(loliga, round = 13, date = LocalDate(year = 2024, month = 7, day = 31), link = Link.round(j = 49, n = 13, z = s"cba2174e22d84ecee4f35ffb53c1a9a1")) -> Seq(
        Fixture(murcia, celta),
        Fixture(eibar, barcelona),
        Fixture(sociedad, espanyol),
        Fixture(real, osasuna),
        Fixture(betis, atletico),
        Fixture(zaragoza, huesca),
        Fixture(tenerife, mallorca),
        Fixture(malaga, levante),
        Fixture(athletic, jaen),
        Fixture(almeria, valencia),
      ),
      TournamentRound(loliga, round = 14, date = LocalDate(year = 2024, month = 8, day = 2), link = Link.round(j = 49, n = 14, z = s"5d597f3888a92a18aaea5347096e6302")) -> Seq(
        Fixture(celta, eibar),
        Fixture(barcelona, sociedad),
        Fixture(espanyol, real),
        Fixture(osasuna, betis),
        Fixture(atletico, zaragoza),
        Fixture(huesca, tenerife),
        Fixture(mallorca, malaga),
        Fixture(levante, athletic),
        Fixture(jaen, almeria),
        Fixture(valencia, murcia),
      ),
      TournamentRound(loliga, round = 15, date = LocalDate(year = 2024, month = 8, day = 7), link = Link.round(j = 49, n = 15, z = s"20cb752e435b6226893e1341216fbc48")) -> Seq(
        Fixture(murcia, eibar),
        Fixture(sociedad, celta),
        Fixture(real, barcelona),
        Fixture(betis, espanyol),
        Fixture(zaragoza, osasuna),
        Fixture(tenerife, atletico),
        Fixture(malaga, huesca),
        Fixture(athletic, mallorca),
        Fixture(almeria, levante),
        Fixture(valencia, jaen),
      ),
      TournamentRound(loliga, round = 16, date = LocalDate(year = 2024, month = 8, day = 14), link = Link.round(j = 49, n = 16, z = s"3565b9413f7fc6ecfddabbb90b94dd27")) -> Seq(
        Fixture(eibar, sociedad),
        Fixture(celta, real),
        Fixture(barcelona, betis),
        Fixture(espanyol, zaragoza),
        Fixture(osasuna, tenerife),
        Fixture(atletico, malaga),
        Fixture(huesca, athletic),
        Fixture(mallorca, almeria),
        Fixture(levante, valencia),
        Fixture(jaen, murcia),
      ),
      TournamentRound(loliga, round = 17, date = LocalDate(year = 2024, month = 8, day = 21), link = Link.round(j = 49, n = 17, z = s"98daeaa98b1a4b137fe0330c6d20ea68")) -> Seq(
        Fixture(murcia, sociedad),
        Fixture(real, eibar),
        Fixture(betis, celta),
        Fixture(zaragoza, barcelona),
        Fixture(tenerife, espanyol),
        Fixture(malaga, osasuna),
        Fixture(athletic, atletico),
        Fixture(almeria, huesca),
        Fixture(valencia, mallorca),
        Fixture(jaen, levante),
      ),
      TournamentRound(loliga, round = 18, date = LocalDate(year = 2024, month = 8, day = 28), link = Link.round(j = 49, n = 18, z = s"039b62edc03ebf874aa94384a228980b")) -> Seq(
        Fixture(sociedad, real),
        Fixture(eibar, betis),
        Fixture(celta, zaragoza),
        Fixture(barcelona, tenerife),
        Fixture(espanyol, malaga),
        Fixture(osasuna, athletic),
        Fixture(atletico, almeria),
        Fixture(huesca, valencia),
        Fixture(mallorca, jaen),
        Fixture(levante, murcia),
      ),
      TournamentRound(loliga, round = 19, date = LocalDate(year = 2024, month = 9, day = 2), link = Link.round(j = 49, n = 19, z = s"082d3bfb3dae291c25fc90ecbfd6c65f")) -> Seq(
        Fixture(murcia, real),
        Fixture(betis, sociedad),
        Fixture(zaragoza, eibar),
        Fixture(tenerife, celta),
        Fixture(malaga, barcelona),
        Fixture(athletic, espanyol),
        Fixture(almeria, osasuna),
        Fixture(valencia, atletico),
        Fixture(jaen, huesca),
        Fixture(levante, mallorca),
      ),
      TournamentRound(loliga, round = 20, date = LocalDate(year = 2024, month = 9, day = 6), link = Link.round(j = 49, n = 20, z = s"c54995a10b4602f3f33efe3b06a6efb5")) -> Seq(
        Fixture(mallorca, murcia),
        Fixture(levante, huesca),
        Fixture(jaen, atletico),
        Fixture(valencia, osasuna),
        Fixture(almeria, espanyol),
        Fixture(athletic, barcelona),
        Fixture(malaga, celta),
        Fixture(tenerife, eibar),
        Fixture(zaragoza, sociedad),
        Fixture(betis, real),
      ),
      TournamentRound(loliga, round = 21, date = LocalDate(year = 2024, month = 9, day = 9), link = Link.round(j = 49, n = 21, z = s"9c95978287651bbb2fd47804dc4e18e7")) -> Seq(
        Fixture(huesca, mallorca),
        Fixture(atletico, levante),
        Fixture(osasuna, jaen),
        Fixture(espanyol, valencia),
        Fixture(barcelona, almeria),
        Fixture(celta, athletic),
        Fixture(eibar, malaga),
        Fixture(sociedad, tenerife),
        Fixture(real, zaragoza),
        Fixture(murcia, betis),
      ),
      TournamentRound(loliga, round = 22, date = LocalDate(year = 2024, month = 9, day = 16), link = Link.round(j = 49, n = 22, z = s"2ba9b7c4302404b9a9835f9b0c493a3d")) -> Seq(
        Fixture(huesca, murcia),
        Fixture(mallorca, atletico),
        Fixture(levante, osasuna),
        Fixture(jaen, espanyol),
        Fixture(valencia, barcelona),
        Fixture(almeria, celta),
        Fixture(athletic, eibar),
        Fixture(malaga, sociedad),
        Fixture(tenerife, real),
        Fixture(zaragoza, betis),
      ),
      TournamentRound(loliga, round = 23, date = LocalDate(year = 2024, month = 9, day = 18), link = Link.round(j = 49, n = 23, z = s"e68f86870ed797cd22cd2409dc73b2e2")) -> Seq(
        Fixture(atletico, huesca),
        Fixture(osasuna, mallorca),
        Fixture(espanyol, levante),
        Fixture(barcelona, jaen),
        Fixture(celta, valencia),
        Fixture(eibar, almeria),
        Fixture(sociedad, athletic),
        Fixture(real, malaga),
        Fixture(betis, tenerife),
        Fixture(murcia, zaragoza),
      ),
      TournamentRound(loliga, round = 24, date = LocalDate(year = 2024, month = 9, day = 23), link = Link.round(j = 49, n = 24, z = s"1eb29c96fbd2456948e918a2ac2bf0f8")) -> Seq(
        Fixture(atletico, murcia),
        Fixture(huesca, osasuna),
        Fixture(mallorca, espanyol),
        Fixture(levante, barcelona),
        Fixture(jaen, celta),
        Fixture(valencia, eibar),
        Fixture(almeria, sociedad),
        Fixture(athletic, real),
        Fixture(malaga, betis),
        Fixture(tenerife, zaragoza),
      ),
      TournamentRound(loliga, round = 25, date = LocalDate(year = 2024, month = 9, day = 30), link = Link.round(j = 49, n = 25, z = s"61a11106e44ab2c07e4c86043cf13d32")) -> Seq(
        Fixture(osasuna, atletico),
        Fixture(espanyol, huesca),
        Fixture(barcelona, mallorca),
        Fixture(celta, levante),
        Fixture(eibar, jaen),
        Fixture(sociedad, valencia),
        Fixture(real, almeria),
        Fixture(betis, athletic),
        Fixture(zaragoza, malaga),
        Fixture(murcia, tenerife),
      ),
      TournamentRound(loliga, round = 26, date = LocalDate(year = 2024, month = 10, day = 2), link = Link.round(j = 49, n = 26, z = s"cc0acf9464434394cc1e82b629937d90")) -> Seq(
        Fixture(osasuna, murcia),
        Fixture(atletico, espanyol),
        Fixture(huesca, barcelona),
        Fixture(mallorca, celta),
        Fixture(levante, eibar),
        Fixture(jaen, sociedad),
        Fixture(valencia, real),
        Fixture(almeria, betis),
        Fixture(athletic, zaragoza),
        Fixture(malaga, tenerife),
      ),
      TournamentRound(loliga, round = 27, date = LocalDate(year = 2024, month = 10, day = 9), link = Link.round(j = 49, n = 27, z = s"becd34100435ae0dc733e63ea2be1749")) -> Seq(
        Fixture(espanyol, osasuna),
        Fixture(barcelona, atletico),
        Fixture(celta, huesca),
        Fixture(eibar, mallorca),
        Fixture(sociedad, levante),
        Fixture(real, jaen),
        Fixture(betis, valencia),
        Fixture(zaragoza, almeria),
        Fixture(tenerife, athletic),
        Fixture(murcia, malaga),
      ),
      TournamentRound(loliga, round = 28, date = LocalDate(year = 2024, month = 10, day = 14), link = Link.round(j = 49, n = 28, z = s"2be54b100fa510e808475bab87b9d9b8")) -> Seq(
        Fixture(espanyol, murcia),
        Fixture(osasuna, barcelona),
        Fixture(atletico, celta),
        Fixture(huesca, eibar),
        Fixture(mallorca, sociedad),
        Fixture(levante, real),
        Fixture(jaen, betis),
        Fixture(valencia, zaragoza),
        Fixture(almeria, tenerife),
        Fixture(athletic, malaga),
      ),
      TournamentRound(loliga, round = 29, date = LocalDate(year = 2024, month = 10, day = 18), link = Link.round(j = 49, n = 29, z = s"cc6d44a81423cfb511876d86f5637793")) -> Seq(
        Fixture(barcelona, espanyol),
        Fixture(celta, osasuna),
        Fixture(eibar, atletico),
        Fixture(sociedad, huesca),
        Fixture(real, mallorca),
        Fixture(betis, levante),
        Fixture(zaragoza, jaen),
        Fixture(tenerife, valencia),
        Fixture(malaga, almeria),
        Fixture(murcia, athletic),
      ),
      TournamentRound(loliga, round = 30, date = LocalDate(year = 2024, month = 10, day = 21), link = Link.round(j = 49, n = 30, z = s"1e87c32a7aabf4a74806a71401c22199")) -> Seq(
        Fixture(barcelona, murcia),
        Fixture(espanyol, celta),
        Fixture(osasuna, eibar),
        Fixture(atletico, sociedad),
        Fixture(huesca, real),
        Fixture(mallorca, betis),
        Fixture(levante, zaragoza),
        Fixture(jaen, tenerife),
        Fixture(valencia, malaga),
        Fixture(almeria, athletic),
      ),
      TournamentRound(loliga, round = 31, date = LocalDate(year = 2024, month = 10, day = 28), link = Link.round(j = 49, n = 31, z = s"8a2e2e77533374504b96f735df6425d6")) -> Seq(
        Fixture(celta, barcelona),
        Fixture(eibar, espanyol),
        Fixture(sociedad, osasuna),
        Fixture(real, atletico),
        Fixture(betis, huesca),
        Fixture(zaragoza, mallorca),
        Fixture(tenerife, levante),
        Fixture(malaga, jaen),
        Fixture(athletic, valencia),
        Fixture(murcia, almeria),
      ),
      TournamentRound(loliga, round = 32, date = LocalDate(year = 2024, month = 10, day = 30), link = Link.round(j = 49, n = 32, z = s"04fd6e4d8a02177b9785ac592e25168e")) -> Seq(
        Fixture(celta, murcia),
        Fixture(barcelona, eibar),
        Fixture(espanyol, sociedad),
        Fixture(osasuna, real),
        Fixture(atletico, betis),
        Fixture(huesca, zaragoza),
        Fixture(mallorca, tenerife),
        Fixture(levante, malaga),
        Fixture(jaen, athletic),
        Fixture(valencia, almeria),
      ),
      TournamentRound(loliga, round = 33, date = LocalDate(year = 2024, month = 11, day = 6), link = Link.round(j = 49, n = 33, z = s"4e5b978f3a209176fab7378411b799c1")) -> Seq(
        Fixture(eibar, celta),
        Fixture(sociedad, barcelona),
        Fixture(real, espanyol),
        Fixture(betis, osasuna),
        Fixture(zaragoza, atletico),
        Fixture(tenerife, huesca),
        Fixture(malaga, mallorca),
        Fixture(athletic, levante),
        Fixture(almeria, jaen),
        Fixture(murcia, valencia),
      ),
      TournamentRound(loliga, round = 34, date = LocalDate(year = 2024, month = 11, day = 8), link = Link.round(j = 49, n = 34, z = s"76a30bf0fccf1856aa76f8faf7406f88")) -> Seq(
        Fixture(eibar, murcia),
        Fixture(celta, sociedad),
        Fixture(barcelona, real),
        Fixture(espanyol, betis),
        Fixture(osasuna, zaragoza),
        Fixture(atletico, tenerife),
        Fixture(huesca, malaga),
        Fixture(mallorca, athletic),
        Fixture(levante, almeria),
        Fixture(jaen, valencia),
      ),
      TournamentRound(loliga, round = 35, date = LocalDate(year = 2024, month = 11, day = 13), link = Link.round(j = 49, n = 35, z = s"a747d358541042b7bcf51dc31cc47d9a")) -> Seq(
        Fixture(sociedad, eibar),
        Fixture(real, celta),
        Fixture(betis, barcelona),
        Fixture(zaragoza, espanyol),
        Fixture(tenerife, osasuna),
        Fixture(malaga, atletico),
        Fixture(athletic, huesca),
        Fixture(almeria, mallorca),
        Fixture(valencia, levante),
        Fixture(murcia, jaen),
      ),
      TournamentRound(loliga, round = 36, date = LocalDate(year = 2024, month = 11, day = 18), link = Link.round(j = 49, n = 36, z = s"2d617e9acae82d79c4f53d8a21890a72")) -> Seq(
        Fixture(sociedad, murcia),
        Fixture(eibar, real),
        Fixture(celta, betis),
        Fixture(barcelona, zaragoza),
        Fixture(espanyol, tenerife),
        Fixture(osasuna, malaga),
        Fixture(atletico, athletic),
        Fixture(huesca, almeria),
        Fixture(mallorca, valencia),
        Fixture(levante, jaen),
      ),
      TournamentRound(loliga, round = 37, date = LocalDate(year = 2024, month = 11, day = 22), link = Link.round(j = 49, n = 37, z = s"f23f2742a1de15c86f7d954fe567a3d0")) -> Seq(
        Fixture(real, sociedad),
        Fixture(betis, eibar),
        Fixture(zaragoza, celta),
        Fixture(tenerife, barcelona),
        Fixture(malaga, espanyol),
        Fixture(athletic, osasuna),
        Fixture(almeria, atletico),
        Fixture(valencia, huesca),
        Fixture(jaen, mallorca),
        Fixture(murcia, levante),
      ),
      TournamentRound(loliga, round = 38, date = LocalDate(year = 2024, month = 11, day = 25), link = Link.round(j = 49, n = 38, z = s"7b925f8a1b9ef7360dded6574b9dabe4")) -> Seq(
        Fixture(real, murcia),
        Fixture(sociedad, betis),
        Fixture(eibar, zaragoza),
        Fixture(celta, tenerife),
        Fixture(barcelona, malaga),
        Fixture(espanyol, athletic),
        Fixture(osasuna, almeria),
        Fixture(atletico, valencia),
        Fixture(huesca, jaen),
        Fixture(mallorca, levante),
      ),
    ).sortBy(_._1.date)
  }

}
